services:
  - type: static_site
    name: jetana-beauty-lounge
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - path: "/*"
        destination: /index.html
